sudo: required

language: java
jdk:
- openjdk7

services:
- docker

before_install:
- docker pull cccb/mev-rserve
- docker run -p 6311:6311 cccb/mev-rserve
# TODO: elastic search setup
- docker ps -a

env:
- RSERVE_SERVICE_HOST="127.0.0.1"
- RSERVE_SERVICE_PORT="6311"

script:
- mvn verify
