before_install:
    - sudo apt-get install gcc
    - pushd /tmp; wget http://cran.r-project.org/src/base/R-2/R-2.15.3.tar.gz; tar xvzf R-2.15.3.tar.gz; cd R-2.15.3; ./configure --with-x=no; make && sudo make install; popd
    - sudo echo "install.packages('DBI', repos='http://cran.rstudio.com/')" | sudo R --no-save
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"limma\")" | sudo R --no-save
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"multtest\")" | sudo R --no-save
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"DESeq\")" | sudo R --no-save
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"topGO\");biocLite(\"org.Hs.eg.db\");biocLite(\"org.Mm.eg.db\");biocLite(\"org.Rn.eg.db\")" | sudo R --no-save
language: java
jdk:
    - oraclejdk7
    - openjdk7
