sudo: required

language: java
jdk:
- openjdk8

services:
- docker

before_install:
- "docker pull $(cat src/main/kubernetes/rserve.yaml | grep 'image: ' | awk -F'image: ' '{print $2}')"
- "docker run -d -p 6311:6311 $(cat src/main/kubernetes/rserve.yaml | grep 'image: ' | awk -F'image: ' '{print $2}')"
# TODO: elastic search setup
- docker ps -a

env:
- RSERVE_SERVICE_HOST="127.0.0.1" RSERVE_SERVICE_PORT="6311"

script:
- mvn verify
