before_install:
    - sudo apt-get update
    - sudo apt-get install r-base
    - sudo echo "install.packages('DBI')" | sudo R --no-save
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"limma\")" | sudo R --no-save
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"multtest\")" | sudo R --no-save
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"DESeq\")" | sudo R --no-save
    - sudo echo "source(\"http://bioconductor.org/biocLite.R\");biocLite(\"topGO\");biocLite(\"org.Hs.eg.db\");biocLite(\"org.Mm.eg.db\");biocLite(\"org.Rn.eg.db\")" | sudo R --no-save
language: java
jdk:
    - oraclejdk7
    - openjdk7
