apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rserve
  spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rserve
    spec:
      containers:
      - name: rserve
        image: docker.io/cccb/mev-rserve:2017-01-05
        ports:
        - containerPort: 6311